server:
  port: 7071

spring:
  profiles:
    active: ${package.environment}
  application:
    name: application_backStage
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
