// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abnormal/abnormal.proto

package com.bmts.heating.commons.grpc.lib.services.abnormal;

public final class AbnormalOuterClass {
  private AbnormalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface abnormalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:abnormal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 ts = 1;</code>
     */
    long getTs();

    /**
     * <code>int32 groupid = 2;</code>
     */
    int getGroupid();

    /**
     * <code>int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>int32 type = 4;</code>
     */
    int getType();

    /**
     * <code>string value = 5;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>string msg = 6;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 6;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>string point = 7;</code>
     */
    java.lang.String getPoint();
    /**
     * <code>string point = 7;</code>
     */
    com.google.protobuf.ByteString
        getPointBytes();
  }
  /**
   * Protobuf type {@code abnormal}
   */
  public  static final class abnormal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:abnormal)
      abnormalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use abnormal.newBuilder() to construct.
    private abnormal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private abnormal() {
      ts_ = 0L;
      groupid_ = 0;
      level_ = 0;
      type_ = 0;
      value_ = "";
      msg_ = "";
      point_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private abnormal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ts_ = input.readInt64();
              break;
            }
            case 16: {

              groupid_ = input.readInt32();
              break;
            }
            case 24: {

              level_ = input.readInt32();
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              point_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.internal_static_abnormal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.internal_static_abnormal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.class, com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.Builder.class);
    }

    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    /**
     * <code>int64 ts = 1;</code>
     */
    public long getTs() {
      return ts_;
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private int groupid_;
    /**
     * <code>int32 groupid = 2;</code>
     */
    public int getGroupid() {
      return groupid_;
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 6;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 6;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POINT_FIELD_NUMBER = 7;
    private volatile java.lang.Object point_;
    /**
     * <code>string point = 7;</code>
     */
    public java.lang.String getPoint() {
      java.lang.Object ref = point_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        point_ = s;
        return s;
      }
    }
    /**
     * <code>string point = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPointBytes() {
      java.lang.Object ref = point_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        point_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ts_ != 0L) {
        output.writeInt64(1, ts_);
      }
      if (groupid_ != 0) {
        output.writeInt32(2, groupid_);
      }
      if (level_ != 0) {
        output.writeInt32(3, level_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msg_);
      }
      if (!getPointBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, point_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, ts_);
      }
      if (groupid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, groupid_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msg_);
      }
      if (!getPointBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, point_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal other = (com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal) obj;

      boolean result = true;
      result = result && (getTs()
          == other.getTs());
      result = result && (getGroupid()
          == other.getGroupid());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (getType()
          == other.getType());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && getPoint()
          .equals(other.getPoint());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTs());
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupid();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPoint().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code abnormal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:abnormal)
        com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.internal_static_abnormal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.internal_static_abnormal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.class, com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ts_ = 0L;

        groupid_ = 0;

        level_ = 0;

        type_ = 0;

        value_ = "";

        msg_ = "";

        point_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.internal_static_abnormal_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal build() {
        com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal result = new com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal(this);
        result.ts_ = ts_;
        result.groupid_ = groupid_;
        result.level_ = level_;
        result.type_ = type_;
        result.value_ = value_;
        result.msg_ = msg_;
        result.point_ = point_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal.getDefaultInstance()) return this;
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        if (other.getGroupid() != 0) {
          setGroupid(other.getGroupid());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (!other.getPoint().isEmpty()) {
          point_ = other.point_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long ts_ ;
      /**
       * <code>int64 ts = 1;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>int64 ts = 1;</code>
       */
      public Builder setTs(long value) {
        
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ts = 1;</code>
       */
      public Builder clearTs() {
        
        ts_ = 0L;
        onChanged();
        return this;
      }

      private int groupid_ ;
      /**
       * <code>int32 groupid = 2;</code>
       */
      public int getGroupid() {
        return groupid_;
      }
      /**
       * <code>int32 groupid = 2;</code>
       */
      public Builder setGroupid(int value) {
        
        groupid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 groupid = 2;</code>
       */
      public Builder clearGroupid() {
        
        groupid_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 3;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 5;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 5;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 5;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 6;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 6;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 6;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 6;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object point_ = "";
      /**
       * <code>string point = 7;</code>
       */
      public java.lang.String getPoint() {
        java.lang.Object ref = point_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          point_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string point = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPointBytes() {
        java.lang.Object ref = point_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          point_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string point = 7;</code>
       */
      public Builder setPoint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        point_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string point = 7;</code>
       */
      public Builder clearPoint() {
        
        point_ = getDefaultInstance().getPoint();
        onChanged();
        return this;
      }
      /**
       * <code>string point = 7;</code>
       */
      public Builder setPointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        point_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:abnormal)
    }

    // @@protoc_insertion_point(class_scope:abnormal)
    private static final com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal();
    }

    public static com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<abnormal>
        PARSER = new com.google.protobuf.AbstractParser<abnormal>() {
      @java.lang.Override
      public abnormal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new abnormal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<abnormal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<abnormal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.abnormal.AbnormalOuterClass.abnormal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abnormal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abnormal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027abnormal/abnormal.proto\032\023common/common" +
      ".proto\"o\n\010abnormal\022\n\n\002ts\030\001 \001(\003\022\017\n\007groupi" +
      "d\030\002 \001(\005\022\r\n\005level\030\003 \001(\005\022\014\n\004type\030\004 \001(\005\022\r\n\005" +
      "value\030\005 \001(\t\022\013\n\003msg\030\006 \001(\t\022\r\n\005point\030\007 \001(\t2" +
      ".\n\010Abnormal\022\"\n\006insert\022\t.abnormal\032\013.BoolR" +
      "esult\"\000B5\n3com.bmts.heating.commons.grpc" +
      ".lib.services.abnormalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bmts.heating.commons.grpc.lib.services.common.Common.getDescriptor(),
        }, assigner);
    internal_static_abnormal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_abnormal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abnormal_descriptor,
        new java.lang.String[] { "Ts", "Groupid", "Level", "Type", "Value", "Msg", "Point", });
    com.bmts.heating.commons.grpc.lib.services.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
