// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tdengine/queryPoints.proto

package com.bmts.heating.commons.grpc.lib.services.tdengine;

public final class QueryPointsOuterClass {
  private QueryPointsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code QueryType}
   */
  public enum QueryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>history = 0;</code>
     */
    history(0),
    /**
     * <code>energy = 1;</code>
     */
    energy(1),
    /**
     * <code>abnormal_query = 2;</code>
     */
    abnormal_query(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>history = 0;</code>
     */
    public static final int history_VALUE = 0;
    /**
     * <code>energy = 1;</code>
     */
    public static final int energy_VALUE = 1;
    /**
     * <code>abnormal_query = 2;</code>
     */
    public static final int abnormal_query_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static QueryType valueOf(int value) {
      return forNumber(value);
    }

    public static QueryType forNumber(int value) {
      switch (value) {
        case 0: return history;
        case 1: return energy;
        case 2: return abnormal_query;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<QueryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        QueryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QueryType>() {
            public QueryType findValueByNumber(int number) {
              return QueryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final QueryType[] VALUES = values();

    public static QueryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private QueryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:QueryType)
  }

  /**
   * Protobuf enum {@code Original}
   */
  public enum Original
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>minute = 0;</code>
     */
    minute(0),
    /**
     * <code>Hour = 1;</code>
     */
    Hour(1),
    /**
     * <code>Day = 2;</code>
     */
    Day(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>minute = 0;</code>
     */
    public static final int minute_VALUE = 0;
    /**
     * <code>Hour = 1;</code>
     */
    public static final int Hour_VALUE = 1;
    /**
     * <code>Day = 2;</code>
     */
    public static final int Day_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Original valueOf(int value) {
      return forNumber(value);
    }

    public static Original forNumber(int value) {
      switch (value) {
        case 0: return minute;
        case 1: return Hour;
        case 2: return Day;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Original>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Original> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Original>() {
            public Original findValueByNumber(int number) {
              return Original.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final Original[] VALUES = values();

    public static Original valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Original(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Original)
  }

  public interface QueryListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 startTime = 1;</code>
     */
    long getStartTime();

    /**
     * <code>int64 endTime = 2;</code>
     */
    long getEndTime();

    /**
     * <code>int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>int32 limit = 4;</code>
     */
    int getLimit();

    /**
     * <code>int32 offset = 5;</code>
     */
    int getOffset();

    /**
     * <code>repeated string points = 6;</code>
     */
    java.util.List<java.lang.String>
        getPointsList();
    /**
     * <code>repeated string points = 6;</code>
     */
    int getPointsCount();
    /**
     * <code>repeated string points = 6;</code>
     */
    java.lang.String getPoints(int index);
    /**
     * <code>repeated string points = 6;</code>
     */
    com.google.protobuf.ByteString
        getPointsBytes(int index);

    /**
     * <code>repeated int32 groupid = 7;</code>
     */
    java.util.List<java.lang.Integer> getGroupidList();
    /**
     * <code>repeated int32 groupid = 7;</code>
     */
    int getGroupidCount();
    /**
     * <code>repeated int32 groupid = 7;</code>
     */
    int getGroupid(int index);

    /**
     * <code>string tableName = 8;</code>
     */
    java.lang.String getTableName();
    /**
     * <code>string tableName = 8;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>.Original original = 9;</code>
     */
    int getOriginalValue();
    /**
     * <code>.Original original = 9;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original getOriginal();

    /**
     * <code>.QueryType queryType = 10;</code>
     */
    int getQueryTypeValue();
    /**
     * <code>.QueryType queryType = 10;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType getQueryType();

    /**
     * <code>string order = 11;</code>
     */
    java.lang.String getOrder();
    /**
     * <code>string order = 11;</code>
     */
    com.google.protobuf.ByteString
        getOrderBytes();

    /**
     * <code>int32 abnormalType = 12;</code>
     */
    int getAbnormalType();
  }
  /**
   * Protobuf type {@code QueryList}
   */
  public  static final class QueryList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QueryList)
      QueryListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryList.newBuilder() to construct.
    private QueryList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryList() {
      startTime_ = 0L;
      endTime_ = 0L;
      level_ = 0;
      limit_ = 0;
      offset_ = 0;
      points_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      groupid_ = java.util.Collections.emptyList();
      tableName_ = "";
      original_ = 0;
      queryType_ = 0;
      order_ = "";
      abnormalType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              startTime_ = input.readInt64();
              break;
            }
            case 16: {

              endTime_ = input.readInt64();
              break;
            }
            case 24: {

              level_ = input.readInt32();
              break;
            }
            case 32: {

              limit_ = input.readInt32();
              break;
            }
            case 40: {

              offset_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                points_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              points_.add(s);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                groupid_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000040;
              }
              groupid_.add(input.readInt32());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                groupid_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                groupid_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              original_ = rawValue;
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              queryType_ = rawValue;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              order_ = s;
              break;
            }
            case 96: {

              abnormalType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          points_ = points_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          groupid_ = java.util.Collections.unmodifiableList(groupid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_QueryList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_QueryList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.Builder.class);
    }

    private int bitField0_;
    public static final int STARTTIME_FIELD_NUMBER = 1;
    private long startTime_;
    /**
     * <code>int64 startTime = 1;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private long endTime_;
    /**
     * <code>int64 endTime = 2;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int LIMIT_FIELD_NUMBER = 4;
    private int limit_;
    /**
     * <code>int32 limit = 4;</code>
     */
    public int getLimit() {
      return limit_;
    }

    public static final int OFFSET_FIELD_NUMBER = 5;
    private int offset_;
    /**
     * <code>int32 offset = 5;</code>
     */
    public int getOffset() {
      return offset_;
    }

    public static final int POINTS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList points_;
    /**
     * <code>repeated string points = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPointsList() {
      return points_;
    }
    /**
     * <code>repeated string points = 6;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated string points = 6;</code>
     */
    public java.lang.String getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated string points = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPointsBytes(int index) {
      return points_.getByteString(index);
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Integer> groupid_;
    /**
     * <code>repeated int32 groupid = 7;</code>
     */
    public java.util.List<java.lang.Integer>
        getGroupidList() {
      return groupid_;
    }
    /**
     * <code>repeated int32 groupid = 7;</code>
     */
    public int getGroupidCount() {
      return groupid_.size();
    }
    /**
     * <code>repeated int32 groupid = 7;</code>
     */
    public int getGroupid(int index) {
      return groupid_.get(index);
    }
    private int groupidMemoizedSerializedSize = -1;

    public static final int TABLENAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object tableName_;
    /**
     * <code>string tableName = 8;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <code>string tableName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINAL_FIELD_NUMBER = 9;
    private int original_;
    /**
     * <code>.Original original = 9;</code>
     */
    public int getOriginalValue() {
      return original_;
    }
    /**
     * <code>.Original original = 9;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original getOriginal() {
      @SuppressWarnings("deprecation")
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.valueOf(original_);
      return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.UNRECOGNIZED : result;
    }

    public static final int QUERYTYPE_FIELD_NUMBER = 10;
    private int queryType_;
    /**
     * <code>.QueryType queryType = 10;</code>
     */
    public int getQueryTypeValue() {
      return queryType_;
    }
    /**
     * <code>.QueryType queryType = 10;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType getQueryType() {
      @SuppressWarnings("deprecation")
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType.valueOf(queryType_);
      return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType.UNRECOGNIZED : result;
    }

    public static final int ORDER_FIELD_NUMBER = 11;
    private volatile java.lang.Object order_;
    /**
     * <code>string order = 11;</code>
     */
    public java.lang.String getOrder() {
      java.lang.Object ref = order_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        order_ = s;
        return s;
      }
    }
    /**
     * <code>string order = 11;</code>
     */
    public com.google.protobuf.ByteString
        getOrderBytes() {
      java.lang.Object ref = order_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        order_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABNORMALTYPE_FIELD_NUMBER = 12;
    private int abnormalType_;
    /**
     * <code>int32 abnormalType = 12;</code>
     */
    public int getAbnormalType() {
      return abnormalType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (startTime_ != 0L) {
        output.writeInt64(1, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(2, endTime_);
      }
      if (level_ != 0) {
        output.writeInt32(3, level_);
      }
      if (limit_ != 0) {
        output.writeInt32(4, limit_);
      }
      if (offset_ != 0) {
        output.writeInt32(5, offset_);
      }
      for (int i = 0; i < points_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, points_.getRaw(i));
      }
      if (getGroupidList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(groupidMemoizedSerializedSize);
      }
      for (int i = 0; i < groupid_.size(); i++) {
        output.writeInt32NoTag(groupid_.get(i));
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tableName_);
      }
      if (original_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.minute.getNumber()) {
        output.writeEnum(9, original_);
      }
      if (queryType_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType.history.getNumber()) {
        output.writeEnum(10, queryType_);
      }
      if (!getOrderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, order_);
      }
      if (abnormalType_ != 0) {
        output.writeInt32(12, abnormalType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, endTime_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, limit_);
      }
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, offset_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < points_.size(); i++) {
          dataSize += computeStringSizeNoTag(points_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPointsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groupid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(groupid_.get(i));
        }
        size += dataSize;
        if (!getGroupidList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        groupidMemoizedSerializedSize = dataSize;
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tableName_);
      }
      if (original_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.minute.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, original_);
      }
      if (queryType_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType.history.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, queryType_);
      }
      if (!getOrderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, order_);
      }
      if (abnormalType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, abnormalType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList other = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList) obj;

      boolean result = true;
      result = result && (getStartTime()
          == other.getStartTime());
      result = result && (getEndTime()
          == other.getEndTime());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (getLimit()
          == other.getLimit());
      result = result && (getOffset()
          == other.getOffset());
      result = result && getPointsList()
          .equals(other.getPointsList());
      result = result && getGroupidList()
          .equals(other.getGroupidList());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && original_ == other.original_;
      result = result && queryType_ == other.queryType_;
      result = result && getOrder()
          .equals(other.getOrder());
      result = result && (getAbnormalType()
          == other.getAbnormalType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      if (getPointsCount() > 0) {
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getPointsList().hashCode();
      }
      if (getGroupidCount() > 0) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupidList().hashCode();
      }
      hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + ORIGINAL_FIELD_NUMBER;
      hash = (53 * hash) + original_;
      hash = (37 * hash) + QUERYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + queryType_;
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getOrder().hashCode();
      hash = (37 * hash) + ABNORMALTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getAbnormalType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryList)
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_QueryList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_QueryList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startTime_ = 0L;

        endTime_ = 0L;

        level_ = 0;

        limit_ = 0;

        offset_ = 0;

        points_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        groupid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        tableName_ = "";

        original_ = 0;

        queryType_ = 0;

        order_ = "";

        abnormalType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_QueryList_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList build() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList result = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        result.level_ = level_;
        result.limit_ = limit_;
        result.offset_ = offset_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          points_ = points_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.points_ = points_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          groupid_ = java.util.Collections.unmodifiableList(groupid_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.groupid_ = groupid_;
        result.tableName_ = tableName_;
        result.original_ = original_;
        result.queryType_ = queryType_;
        result.order_ = order_;
        result.abnormalType_ = abnormalType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList.getDefaultInstance()) return this;
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          onChanged();
        }
        if (!other.groupid_.isEmpty()) {
          if (groupid_.isEmpty()) {
            groupid_ = other.groupid_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureGroupidIsMutable();
            groupid_.addAll(other.groupid_);
          }
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.original_ != 0) {
          setOriginalValue(other.getOriginalValue());
        }
        if (other.queryType_ != 0) {
          setQueryTypeValue(other.getQueryTypeValue());
        }
        if (!other.getOrder().isEmpty()) {
          order_ = other.order_;
          onChanged();
        }
        if (other.getAbnormalType() != 0) {
          setAbnormalType(other.getAbnormalType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startTime_ ;
      /**
       * <code>int64 startTime = 1;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 startTime = 1;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startTime = 1;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 endTime = 2;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 endTime = 2;</code>
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 endTime = 2;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 3;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <code>int32 limit = 4;</code>
       */
      public int getLimit() {
        return limit_;
      }
      /**
       * <code>int32 limit = 4;</code>
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 limit = 4;</code>
       */
      public Builder clearLimit() {
        
        limit_ = 0;
        onChanged();
        return this;
      }

      private int offset_ ;
      /**
       * <code>int32 offset = 5;</code>
       */
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>int32 offset = 5;</code>
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 offset = 5;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList points_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          points_ = new com.google.protobuf.LazyStringArrayList(points_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPointsList() {
        return points_.getUnmodifiableView();
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public int getPointsCount() {
        return points_.size();
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public java.lang.String getPoints(int index) {
        return points_.get(index);
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPointsBytes(int index) {
        return points_.getByteString(index);
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public Builder setPoints(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePointsIsMutable();
        points_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public Builder addPoints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePointsIsMutable();
        points_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<java.lang.String> values) {
        ensurePointsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, points_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public Builder clearPoints() {
        points_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string points = 6;</code>
       */
      public Builder addPointsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePointsIsMutable();
        points_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> groupid_ = java.util.Collections.emptyList();
      private void ensureGroupidIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          groupid_ = new java.util.ArrayList<java.lang.Integer>(groupid_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public java.util.List<java.lang.Integer>
          getGroupidList() {
        return java.util.Collections.unmodifiableList(groupid_);
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public int getGroupidCount() {
        return groupid_.size();
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public int getGroupid(int index) {
        return groupid_.get(index);
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public Builder setGroupid(
          int index, int value) {
        ensureGroupidIsMutable();
        groupid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public Builder addGroupid(int value) {
        ensureGroupidIsMutable();
        groupid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public Builder addAllGroupid(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGroupidIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 groupid = 7;</code>
       */
      public Builder clearGroupid() {
        groupid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <code>string tableName = 8;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tableName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tableName = 8;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tableName = 8;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string tableName = 8;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private int original_ = 0;
      /**
       * <code>.Original original = 9;</code>
       */
      public int getOriginalValue() {
        return original_;
      }
      /**
       * <code>.Original original = 9;</code>
       */
      public Builder setOriginalValue(int value) {
        original_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Original original = 9;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original getOriginal() {
        @SuppressWarnings("deprecation")
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.valueOf(original_);
        return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.UNRECOGNIZED : result;
      }
      /**
       * <code>.Original original = 9;</code>
       */
      public Builder setOriginal(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        original_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Original original = 9;</code>
       */
      public Builder clearOriginal() {
        
        original_ = 0;
        onChanged();
        return this;
      }

      private int queryType_ = 0;
      /**
       * <code>.QueryType queryType = 10;</code>
       */
      public int getQueryTypeValue() {
        return queryType_;
      }
      /**
       * <code>.QueryType queryType = 10;</code>
       */
      public Builder setQueryTypeValue(int value) {
        queryType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.QueryType queryType = 10;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType getQueryType() {
        @SuppressWarnings("deprecation")
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType.valueOf(queryType_);
        return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType.UNRECOGNIZED : result;
      }
      /**
       * <code>.QueryType queryType = 10;</code>
       */
      public Builder setQueryType(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        queryType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.QueryType queryType = 10;</code>
       */
      public Builder clearQueryType() {
        
        queryType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object order_ = "";
      /**
       * <code>string order = 11;</code>
       */
      public java.lang.String getOrder() {
        java.lang.Object ref = order_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          order_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string order = 11;</code>
       */
      public com.google.protobuf.ByteString
          getOrderBytes() {
        java.lang.Object ref = order_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          order_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string order = 11;</code>
       */
      public Builder setOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string order = 11;</code>
       */
      public Builder clearOrder() {
        
        order_ = getDefaultInstance().getOrder();
        onChanged();
        return this;
      }
      /**
       * <code>string order = 11;</code>
       */
      public Builder setOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        order_ = value;
        onChanged();
        return this;
      }

      private int abnormalType_ ;
      /**
       * <code>int32 abnormalType = 12;</code>
       */
      public int getAbnormalType() {
        return abnormalType_;
      }
      /**
       * <code>int32 abnormalType = 12;</code>
       */
      public Builder setAbnormalType(int value) {
        
        abnormalType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 abnormalType = 12;</code>
       */
      public Builder clearAbnormalType() {
        
        abnormalType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QueryList)
    }

    // @@protoc_insertion_point(class_scope:QueryList)
    private static final com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList();
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryList>
        PARSER = new com.google.protobuf.AbstractParser<QueryList>() {
      @java.lang.Override
      public QueryList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.QueryList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 total = 1;</code>
     */
    int getTotal();

    /**
     * <code>string jsonData = 2;</code>
     */
    java.lang.String getJsonData();
    /**
     * <code>string jsonData = 2;</code>
     */
    com.google.protobuf.ByteString
        getJsonDataBytes();

    /**
     * <code>string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      total_ = 0;
      jsonData_ = "";
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              total_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              jsonData_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.Builder.class);
    }

    public static final int TOTAL_FIELD_NUMBER = 1;
    private int total_;
    /**
     * <code>int32 total = 1;</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int JSONDATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object jsonData_;
    /**
     * <code>string jsonData = 2;</code>
     */
    public java.lang.String getJsonData() {
      java.lang.Object ref = jsonData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonData_ = s;
        return s;
      }
    }
    /**
     * <code>string jsonData = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJsonDataBytes() {
      java.lang.Object ref = jsonData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (total_ != 0) {
        output.writeInt32(1, total_);
      }
      if (!getJsonDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jsonData_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, error_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (total_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, total_);
      }
      if (!getJsonDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jsonData_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, error_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response other = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response) obj;

      boolean result = true;
      result = result && (getTotal()
          == other.getTotal());
      result = result && getJsonData()
          .equals(other.getJsonData());
      result = result && getError()
          .equals(other.getError());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal();
      hash = (37 * hash) + JSONDATA_FIELD_NUMBER;
      hash = (53 * hash) + getJsonData().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        total_ = 0;

        jsonData_ = "";

        error_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response build() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response result = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response(this);
        result.total_ = total_;
        result.jsonData_ = jsonData_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response.getDefaultInstance()) return this;
        if (other.getTotal() != 0) {
          setTotal(other.getTotal());
        }
        if (!other.getJsonData().isEmpty()) {
          jsonData_ = other.jsonData_;
          onChanged();
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int total_ ;
      /**
       * <code>int32 total = 1;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>int32 total = 1;</code>
       */
      public Builder setTotal(int value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total = 1;</code>
       */
      public Builder clearTotal() {
        
        total_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object jsonData_ = "";
      /**
       * <code>string jsonData = 2;</code>
       */
      public java.lang.String getJsonData() {
        java.lang.Object ref = jsonData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jsonData = 2;</code>
       */
      public com.google.protobuf.ByteString
          getJsonDataBytes() {
        java.lang.Object ref = jsonData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jsonData = 2;</code>
       */
      public Builder setJsonData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jsonData = 2;</code>
       */
      public Builder clearJsonData() {
        
        jsonData_ = getDefaultInstance().getJsonData();
        onChanged();
        return this;
      }
      /**
       * <code>string jsonData = 2;</code>
       */
      public Builder setJsonDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response();
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032tdengine/queryPoints.proto\"\362\001\n\tQueryLi" +
      "st\022\021\n\tstartTime\030\001 \001(\003\022\017\n\007endTime\030\002 \001(\003\022\r" +
      "\n\005level\030\003 \001(\005\022\r\n\005limit\030\004 \001(\005\022\016\n\006offset\030\005" +
      " \001(\005\022\016\n\006points\030\006 \003(\t\022\017\n\007groupid\030\007 \003(\005\022\021\n" +
      "\ttableName\030\010 \001(\t\022\033\n\010original\030\t \001(\0162\t.Ori" +
      "ginal\022\035\n\tqueryType\030\n \001(\0162\n.QueryType\022\r\n\005" +
      "order\030\013 \001(\t\022\024\n\014abnormalType\030\014 \001(\005\":\n\010Res" +
      "ponse\022\r\n\005total\030\001 \001(\005\022\020\n\010jsonData\030\002 \001(\t\022\r" +
      "\n\005error\030\003 \001(\t*8\n\tQueryType\022\013\n\007history\020\000\022" +
      "\n\n\006energy\020\001\022\022\n\016abnormal_query\020\002*)\n\010Origi" +
      "nal\022\n\n\006minute\020\000\022\010\n\004Hour\020\001\022\007\n\003Day\020\00229\n\013Qu" +
      "eryPoints\022*\n\rqueryOriginal\022\n.QueryList\032\t" +
      ".Response\"\0000\001B5\n3com.bmts.heating.common" +
      "s.grpc.lib.services.tdengineb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueryList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryList_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "Level", "Limit", "Offset", "Points", "Groupid", "TableName", "Original", "QueryType", "Order", "AbnormalType", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Total", "JsonData", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
