// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tdengine/queryAggregate.proto

package com.bmts.heating.commons.grpc.lib.services.tdengine;

public final class QueryAggregateOuterClass {
  private QueryAggregateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code GroupType}
   */
  public enum GroupType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>singal = 0;</code>
     */
    singal(0),
    /**
     * <code>group = 1;</code>
     */
    group(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>singal = 0;</code>
     */
    public static final int singal_VALUE = 0;
    /**
     * <code>group = 1;</code>
     */
    public static final int group_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GroupType valueOf(int value) {
      return forNumber(value);
    }

    public static GroupType forNumber(int value) {
      switch (value) {
        case 0: return singal;
        case 1: return group;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GroupType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GroupType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GroupType>() {
            public GroupType findValueByNumber(int number) {
              return GroupType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final GroupType[] VALUES = values();

    public static GroupType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GroupType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GroupType)
  }

  /**
   * Protobuf enum {@code aggregateType}
   */
  public enum aggregateType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>avg = 0;</code>
     */
    avg(0),
    /**
     * <code>sum = 1;</code>
     */
    sum(1),
    /**
     * <code>max = 2;</code>
     */
    max(2),
    /**
     * <code>min = 3;</code>
     */
    min(3),
    /**
     * <code>TWA = 4;</code>
     */
    TWA(4),
    /**
     * <code>STDDEV = 5;</code>
     */
    STDDEV(5),
    /**
     * <code>diff = 6;</code>
     */
    diff(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>avg = 0;</code>
     */
    public static final int avg_VALUE = 0;
    /**
     * <code>sum = 1;</code>
     */
    public static final int sum_VALUE = 1;
    /**
     * <code>max = 2;</code>
     */
    public static final int max_VALUE = 2;
    /**
     * <code>min = 3;</code>
     */
    public static final int min_VALUE = 3;
    /**
     * <code>TWA = 4;</code>
     */
    public static final int TWA_VALUE = 4;
    /**
     * <code>STDDEV = 5;</code>
     */
    public static final int STDDEV_VALUE = 5;
    /**
     * <code>diff = 6;</code>
     */
    public static final int diff_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static aggregateType valueOf(int value) {
      return forNumber(value);
    }

    public static aggregateType forNumber(int value) {
      switch (value) {
        case 0: return avg;
        case 1: return sum;
        case 2: return max;
        case 3: return min;
        case 4: return TWA;
        case 5: return STDDEV;
        case 6: return diff;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<aggregateType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        aggregateType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<aggregateType>() {
            public aggregateType findValueByNumber(int number) {
              return aggregateType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final aggregateType[] VALUES = values();

    public static aggregateType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private aggregateType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:aggregateType)
  }

  public interface aggregateQueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aggregateQuery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 startTime = 1;</code>
     */
    long getStartTime();

    /**
     * <code>int64 endTime = 2;</code>
     */
    long getEndTime();

    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    java.util.List<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint> 
        getPointsList();
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint getPoints(int index);
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    int getPointsCount();
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    java.util.List<? extends com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder> 
        getPointsOrBuilderList();
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder getPointsOrBuilder(
        int index);

    /**
     * <code>repeated int32 groupid = 4;</code>
     */
    java.util.List<java.lang.Integer> getGroupidList();
    /**
     * <code>repeated int32 groupid = 4;</code>
     */
    int getGroupidCount();
    /**
     * <code>repeated int32 groupid = 4;</code>
     */
    int getGroupid(int index);

    /**
     * <code>string tableName = 5;</code>
     */
    java.lang.String getTableName();
    /**
     * <code>string tableName = 5;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>.Original original = 6;</code>
     */
    int getOriginalValue();
    /**
     * <code>.Original original = 6;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original getOriginal();

    /**
     * <code>int32 limit = 7;</code>
     */
    int getLimit();

    /**
     * <code>int32 offset = 8;</code>
     */
    int getOffset();

    /**
     * <code>string order = 9;</code>
     */
    java.lang.String getOrder();
    /**
     * <code>string order = 9;</code>
     */
    com.google.protobuf.ByteString
        getOrderBytes();

    /**
     * <code>.GroupType groupType = 10;</code>
     */
    int getGroupTypeValue();
    /**
     * <code>.GroupType groupType = 10;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType getGroupType();
  }
  /**
   * Protobuf type {@code aggregateQuery}
   */
  public  static final class aggregateQuery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aggregateQuery)
      aggregateQueryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use aggregateQuery.newBuilder() to construct.
    private aggregateQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private aggregateQuery() {
      startTime_ = 0L;
      endTime_ = 0L;
      points_ = java.util.Collections.emptyList();
      groupid_ = java.util.Collections.emptyList();
      tableName_ = "";
      original_ = 0;
      limit_ = 0;
      offset_ = 0;
      order_ = "";
      groupType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private aggregateQuery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              startTime_ = input.readInt64();
              break;
            }
            case 16: {

              endTime_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                points_ = new java.util.ArrayList<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint>();
                mutable_bitField0_ |= 0x00000004;
              }
              points_.add(
                  input.readMessage(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.parser(), extensionRegistry));
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                groupid_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              groupid_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                groupid_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                groupid_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              original_ = rawValue;
              break;
            }
            case 56: {

              limit_ = input.readInt32();
              break;
            }
            case 64: {

              offset_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              order_ = s;
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              groupType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          groupid_ = java.util.Collections.unmodifiableList(groupid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregateQuery_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregateQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.Builder.class);
    }

    private int bitField0_;
    public static final int STARTTIME_FIELD_NUMBER = 1;
    private long startTime_;
    /**
     * <code>int64 startTime = 1;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private long endTime_;
    /**
     * <code>int64 endTime = 2;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int POINTS_FIELD_NUMBER = 3;
    private java.util.List<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint> points_;
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    public java.util.List<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    public java.util.List<? extends com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .aggregatePoint points = 3;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    public static final int GROUPID_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> groupid_;
    /**
     * <code>repeated int32 groupid = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getGroupidList() {
      return groupid_;
    }
    /**
     * <code>repeated int32 groupid = 4;</code>
     */
    public int getGroupidCount() {
      return groupid_.size();
    }
    /**
     * <code>repeated int32 groupid = 4;</code>
     */
    public int getGroupid(int index) {
      return groupid_.get(index);
    }
    private int groupidMemoizedSerializedSize = -1;

    public static final int TABLENAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object tableName_;
    /**
     * <code>string tableName = 5;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <code>string tableName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINAL_FIELD_NUMBER = 6;
    private int original_;
    /**
     * <code>.Original original = 6;</code>
     */
    public int getOriginalValue() {
      return original_;
    }
    /**
     * <code>.Original original = 6;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original getOriginal() {
      @SuppressWarnings("deprecation")
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.valueOf(original_);
      return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.UNRECOGNIZED : result;
    }

    public static final int LIMIT_FIELD_NUMBER = 7;
    private int limit_;
    /**
     * <code>int32 limit = 7;</code>
     */
    public int getLimit() {
      return limit_;
    }

    public static final int OFFSET_FIELD_NUMBER = 8;
    private int offset_;
    /**
     * <code>int32 offset = 8;</code>
     */
    public int getOffset() {
      return offset_;
    }

    public static final int ORDER_FIELD_NUMBER = 9;
    private volatile java.lang.Object order_;
    /**
     * <code>string order = 9;</code>
     */
    public java.lang.String getOrder() {
      java.lang.Object ref = order_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        order_ = s;
        return s;
      }
    }
    /**
     * <code>string order = 9;</code>
     */
    public com.google.protobuf.ByteString
        getOrderBytes() {
      java.lang.Object ref = order_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        order_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPTYPE_FIELD_NUMBER = 10;
    private int groupType_;
    /**
     * <code>.GroupType groupType = 10;</code>
     */
    public int getGroupTypeValue() {
      return groupType_;
    }
    /**
     * <code>.GroupType groupType = 10;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType getGroupType() {
      @SuppressWarnings("deprecation")
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType.valueOf(groupType_);
      return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (startTime_ != 0L) {
        output.writeInt64(1, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(2, endTime_);
      }
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(3, points_.get(i));
      }
      if (getGroupidList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(groupidMemoizedSerializedSize);
      }
      for (int i = 0; i < groupid_.size(); i++) {
        output.writeInt32NoTag(groupid_.get(i));
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tableName_);
      }
      if (original_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.minute.getNumber()) {
        output.writeEnum(6, original_);
      }
      if (limit_ != 0) {
        output.writeInt32(7, limit_);
      }
      if (offset_ != 0) {
        output.writeInt32(8, offset_);
      }
      if (!getOrderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, order_);
      }
      if (groupType_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType.singal.getNumber()) {
        output.writeEnum(10, groupType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, endTime_);
      }
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, points_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groupid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(groupid_.get(i));
        }
        size += dataSize;
        if (!getGroupidList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        groupidMemoizedSerializedSize = dataSize;
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tableName_);
      }
      if (original_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.minute.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, original_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, limit_);
      }
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, offset_);
      }
      if (!getOrderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, order_);
      }
      if (groupType_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType.singal.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, groupType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery other = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery) obj;

      boolean result = true;
      result = result && (getStartTime()
          == other.getStartTime());
      result = result && (getEndTime()
          == other.getEndTime());
      result = result && getPointsList()
          .equals(other.getPointsList());
      result = result && getGroupidList()
          .equals(other.getGroupidList());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && original_ == other.original_;
      result = result && (getLimit()
          == other.getLimit());
      result = result && (getOffset()
          == other.getOffset());
      result = result && getOrder()
          .equals(other.getOrder());
      result = result && groupType_ == other.groupType_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      if (getPointsCount() > 0) {
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getPointsList().hashCode();
      }
      if (getGroupidCount() > 0) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupidList().hashCode();
      }
      hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + ORIGINAL_FIELD_NUMBER;
      hash = (53 * hash) + original_;
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getOrder().hashCode();
      hash = (37 * hash) + GROUPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + groupType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aggregateQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aggregateQuery)
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregateQuery_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregateQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPointsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startTime_ = 0L;

        endTime_ = 0L;

        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          pointsBuilder_.clear();
        }
        groupid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        tableName_ = "";

        original_ = 0;

        limit_ = 0;

        offset_ = 0;

        order_ = "";

        groupType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregateQuery_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery build() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery result = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          groupid_ = java.util.Collections.unmodifiableList(groupid_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.groupid_ = groupid_;
        result.tableName_ = tableName_;
        result.original_ = original_;
        result.limit_ = limit_;
        result.offset_ = offset_;
        result.order_ = order_;
        result.groupType_ = groupType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery.getDefaultInstance()) return this;
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000004);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        if (!other.groupid_.isEmpty()) {
          if (groupid_.isEmpty()) {
            groupid_ = other.groupid_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGroupidIsMutable();
            groupid_.addAll(other.groupid_);
          }
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.original_ != 0) {
          setOriginalValue(other.getOriginalValue());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (!other.getOrder().isEmpty()) {
          order_ = other.order_;
          onChanged();
        }
        if (other.groupType_ != 0) {
          setGroupTypeValue(other.getGroupTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startTime_ ;
      /**
       * <code>int64 startTime = 1;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 startTime = 1;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startTime = 1;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 endTime = 2;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 endTime = 2;</code>
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 endTime = 2;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          points_ = new java.util.ArrayList<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint>(points_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder> pointsBuilder_;

      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public java.util.List<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder setPoints(
          int index, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder setPoints(
          int index, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder addPoints(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder addPoints(
          int index, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder addPoints(
          com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder addPoints(
          int index, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public java.util.List<? extends com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder> 
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.getDefaultInstance());
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.getDefaultInstance());
      }
      /**
       * <code>repeated .aggregatePoint points = 3;</code>
       */
      public java.util.List<com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder> 
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }

      private java.util.List<java.lang.Integer> groupid_ = java.util.Collections.emptyList();
      private void ensureGroupidIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          groupid_ = new java.util.ArrayList<java.lang.Integer>(groupid_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getGroupidList() {
        return java.util.Collections.unmodifiableList(groupid_);
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public int getGroupidCount() {
        return groupid_.size();
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public int getGroupid(int index) {
        return groupid_.get(index);
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public Builder setGroupid(
          int index, int value) {
        ensureGroupidIsMutable();
        groupid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public Builder addGroupid(int value) {
        ensureGroupidIsMutable();
        groupid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public Builder addAllGroupid(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGroupidIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 groupid = 4;</code>
       */
      public Builder clearGroupid() {
        groupid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <code>string tableName = 5;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tableName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tableName = 5;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tableName = 5;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string tableName = 5;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private int original_ = 0;
      /**
       * <code>.Original original = 6;</code>
       */
      public int getOriginalValue() {
        return original_;
      }
      /**
       * <code>.Original original = 6;</code>
       */
      public Builder setOriginalValue(int value) {
        original_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Original original = 6;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original getOriginal() {
        @SuppressWarnings("deprecation")
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.valueOf(original_);
        return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original.UNRECOGNIZED : result;
      }
      /**
       * <code>.Original original = 6;</code>
       */
      public Builder setOriginal(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.Original value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        original_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Original original = 6;</code>
       */
      public Builder clearOriginal() {
        
        original_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <code>int32 limit = 7;</code>
       */
      public int getLimit() {
        return limit_;
      }
      /**
       * <code>int32 limit = 7;</code>
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 limit = 7;</code>
       */
      public Builder clearLimit() {
        
        limit_ = 0;
        onChanged();
        return this;
      }

      private int offset_ ;
      /**
       * <code>int32 offset = 8;</code>
       */
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>int32 offset = 8;</code>
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 offset = 8;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object order_ = "";
      /**
       * <code>string order = 9;</code>
       */
      public java.lang.String getOrder() {
        java.lang.Object ref = order_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          order_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string order = 9;</code>
       */
      public com.google.protobuf.ByteString
          getOrderBytes() {
        java.lang.Object ref = order_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          order_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string order = 9;</code>
       */
      public Builder setOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string order = 9;</code>
       */
      public Builder clearOrder() {
        
        order_ = getDefaultInstance().getOrder();
        onChanged();
        return this;
      }
      /**
       * <code>string order = 9;</code>
       */
      public Builder setOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        order_ = value;
        onChanged();
        return this;
      }

      private int groupType_ = 0;
      /**
       * <code>.GroupType groupType = 10;</code>
       */
      public int getGroupTypeValue() {
        return groupType_;
      }
      /**
       * <code>.GroupType groupType = 10;</code>
       */
      public Builder setGroupTypeValue(int value) {
        groupType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.GroupType groupType = 10;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType getGroupType() {
        @SuppressWarnings("deprecation")
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType.valueOf(groupType_);
        return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType.UNRECOGNIZED : result;
      }
      /**
       * <code>.GroupType groupType = 10;</code>
       */
      public Builder setGroupType(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.GroupType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        groupType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.GroupType groupType = 10;</code>
       */
      public Builder clearGroupType() {
        
        groupType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aggregateQuery)
    }

    // @@protoc_insertion_point(class_scope:aggregateQuery)
    private static final com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery();
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<aggregateQuery>
        PARSER = new com.google.protobuf.AbstractParser<aggregateQuery>() {
      @java.lang.Override
      public aggregateQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new aggregateQuery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<aggregateQuery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<aggregateQuery> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateQuery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface aggregatePointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aggregatePoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pointName = 1;</code>
     */
    java.lang.String getPointName();
    /**
     * <code>string pointName = 1;</code>
     */
    com.google.protobuf.ByteString
        getPointNameBytes();

    /**
     * <code>.aggregateType aggregateType = 2;</code>
     */
    int getAggregateTypeValue();
    /**
     * <code>.aggregateType aggregateType = 2;</code>
     */
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType getAggregateType();
  }
  /**
   * Protobuf type {@code aggregatePoint}
   */
  public  static final class aggregatePoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aggregatePoint)
      aggregatePointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use aggregatePoint.newBuilder() to construct.
    private aggregatePoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private aggregatePoint() {
      pointName_ = "";
      aggregateType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private aggregatePoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pointName_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              aggregateType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregatePoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregatePoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder.class);
    }

    public static final int POINTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object pointName_;
    /**
     * <code>string pointName = 1;</code>
     */
    public java.lang.String getPointName() {
      java.lang.Object ref = pointName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pointName_ = s;
        return s;
      }
    }
    /**
     * <code>string pointName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPointNameBytes() {
      java.lang.Object ref = pointName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pointName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGGREGATETYPE_FIELD_NUMBER = 2;
    private int aggregateType_;
    /**
     * <code>.aggregateType aggregateType = 2;</code>
     */
    public int getAggregateTypeValue() {
      return aggregateType_;
    }
    /**
     * <code>.aggregateType aggregateType = 2;</code>
     */
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType getAggregateType() {
      @SuppressWarnings("deprecation")
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType.valueOf(aggregateType_);
      return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPointNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pointName_);
      }
      if (aggregateType_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType.avg.getNumber()) {
        output.writeEnum(2, aggregateType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPointNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pointName_);
      }
      if (aggregateType_ != com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType.avg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, aggregateType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint other = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint) obj;

      boolean result = true;
      result = result && getPointName()
          .equals(other.getPointName());
      result = result && aggregateType_ == other.aggregateType_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POINTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPointName().hashCode();
      hash = (37 * hash) + AGGREGATETYPE_FIELD_NUMBER;
      hash = (53 * hash) + aggregateType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aggregatePoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aggregatePoint)
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregatePoint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregatePoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.class, com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pointName_ = "";

        aggregateType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.internal_static_aggregatePoint_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint build() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint result = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint(this);
        result.pointName_ = pointName_;
        result.aggregateType_ = aggregateType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint.getDefaultInstance()) return this;
        if (!other.getPointName().isEmpty()) {
          pointName_ = other.pointName_;
          onChanged();
        }
        if (other.aggregateType_ != 0) {
          setAggregateTypeValue(other.getAggregateTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pointName_ = "";
      /**
       * <code>string pointName = 1;</code>
       */
      public java.lang.String getPointName() {
        java.lang.Object ref = pointName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pointName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pointName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPointNameBytes() {
        java.lang.Object ref = pointName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pointName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pointName = 1;</code>
       */
      public Builder setPointName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pointName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pointName = 1;</code>
       */
      public Builder clearPointName() {
        
        pointName_ = getDefaultInstance().getPointName();
        onChanged();
        return this;
      }
      /**
       * <code>string pointName = 1;</code>
       */
      public Builder setPointNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pointName_ = value;
        onChanged();
        return this;
      }

      private int aggregateType_ = 0;
      /**
       * <code>.aggregateType aggregateType = 2;</code>
       */
      public int getAggregateTypeValue() {
        return aggregateType_;
      }
      /**
       * <code>.aggregateType aggregateType = 2;</code>
       */
      public Builder setAggregateTypeValue(int value) {
        aggregateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.aggregateType aggregateType = 2;</code>
       */
      public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType getAggregateType() {
        @SuppressWarnings("deprecation")
        com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType result = com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType.valueOf(aggregateType_);
        return result == null ? com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType.UNRECOGNIZED : result;
      }
      /**
       * <code>.aggregateType aggregateType = 2;</code>
       */
      public Builder setAggregateType(com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregateType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        aggregateType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.aggregateType aggregateType = 2;</code>
       */
      public Builder clearAggregateType() {
        
        aggregateType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aggregatePoint)
    }

    // @@protoc_insertion_point(class_scope:aggregatePoint)
    private static final com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint();
    }

    public static com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<aggregatePoint>
        PARSER = new com.google.protobuf.AbstractParser<aggregatePoint>() {
      @java.lang.Override
      public aggregatePoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new aggregatePoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<aggregatePoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<aggregatePoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.tdengine.QueryAggregateOuterClass.aggregatePoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aggregateQuery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aggregateQuery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aggregatePoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aggregatePoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035tdengine/queryAggregate.proto\032\032tdengin" +
      "e/queryPoints.proto\"\343\001\n\016aggregateQuery\022\021" +
      "\n\tstartTime\030\001 \001(\003\022\017\n\007endTime\030\002 \001(\003\022\037\n\006po" +
      "ints\030\003 \003(\0132\017.aggregatePoint\022\017\n\007groupid\030\004" +
      " \003(\005\022\021\n\ttableName\030\005 \001(\t\022\033\n\010original\030\006 \001(" +
      "\0162\t.Original\022\r\n\005limit\030\007 \001(\005\022\016\n\006offset\030\010 " +
      "\001(\005\022\r\n\005order\030\t \001(\t\022\035\n\tgroupType\030\n \001(\0162\n." +
      "GroupType\"J\n\016aggregatePoint\022\021\n\tpointName" +
      "\030\001 \001(\t\022%\n\raggregateType\030\002 \001(\0162\016.aggregat" +
      "eType*\"\n\tGroupType\022\n\n\006singal\020\000\022\t\n\005group\020" +
      "\001*R\n\raggregateType\022\007\n\003avg\020\000\022\007\n\003sum\020\001\022\007\n\003" +
      "max\020\002\022\007\n\003min\020\003\022\007\n\003TWA\020\004\022\n\n\006STDDEV\020\005\022\010\n\004d" +
      "iff\020\00627\n\016QueryAggregate\022%\n\005query\022\017.aggre" +
      "gateQuery\032\t.Response\"\000B5\n3com.bmts.heati" +
      "ng.commons.grpc.lib.services.tdengineb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_aggregateQuery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aggregateQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aggregateQuery_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "Points", "Groupid", "TableName", "Original", "Limit", "Offset", "Order", "GroupType", });
    internal_static_aggregatePoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aggregatePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aggregatePoint_descriptor,
        new java.lang.String[] { "PointName", "AggregateType", });
    com.bmts.heating.commons.grpc.lib.services.tdengine.QueryPointsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
