// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor/monitor.proto

package com.bmts.heating.commons.grpc.lib.services.Monitor;

public final class MonitorOuterClass {
  private MonitorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RectangleMOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RectangleM)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pid = 1;</code>
     */
    int getPid();
  }
  /**
   * Protobuf type {@code RectangleM}
   */
  public  static final class RectangleM extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RectangleM)
      RectangleMOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RectangleM.newBuilder() to construct.
    private RectangleM(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RectangleM() {
      pid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RectangleM(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pid_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_RectangleM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_RectangleM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.class, com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pid_ != 0) {
        output.writeInt32(1, pid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM other = (com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM) obj;

      boolean result = true;
      result = result && (getPid()
          == other.getPid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RectangleM}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RectangleM)
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleMOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_RectangleM_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_RectangleM_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.class, com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pid_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_RectangleM_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM build() {
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM result = new com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM(this);
        result.pid_ = pid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM.getDefaultInstance()) return this;
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pid_ ;
      /**
       * <code>int32 pid = 1;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>int32 pid = 1;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pid = 1;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RectangleM)
    }

    // @@protoc_insertion_point(class_scope:RectangleM)
    private static final com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM();
    }

    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RectangleM>
        PARSER = new com.google.protobuf.AbstractParser<RectangleM>() {
      @java.lang.Override
      public RectangleM parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RectangleM(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RectangleM> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RectangleM> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.RectangleM getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonitorLOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MonitorL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 mloop = 1;</code>
     */
    int getMloop();
  }
  /**
   * Protobuf type {@code MonitorL}
   */
  public  static final class MonitorL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MonitorL)
      MonitorLOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonitorL.newBuilder() to construct.
    private MonitorL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonitorL() {
      mloop_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MonitorL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              mloop_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_MonitorL_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_MonitorL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.class, com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.Builder.class);
    }

    public static final int MLOOP_FIELD_NUMBER = 1;
    private int mloop_;
    /**
     * <code>int32 mloop = 1;</code>
     */
    public int getMloop() {
      return mloop_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mloop_ != 0) {
        output.writeInt32(1, mloop_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mloop_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mloop_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL other = (com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL) obj;

      boolean result = true;
      result = result && (getMloop()
          == other.getMloop());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MLOOP_FIELD_NUMBER;
      hash = (53 * hash) + getMloop();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MonitorL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MonitorL)
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorLOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_MonitorL_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_MonitorL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.class, com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mloop_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.internal_static_MonitorL_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL build() {
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL result = new com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL(this);
        result.mloop_ = mloop_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL.getDefaultInstance()) return this;
        if (other.getMloop() != 0) {
          setMloop(other.getMloop());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mloop_ ;
      /**
       * <code>int32 mloop = 1;</code>
       */
      public int getMloop() {
        return mloop_;
      }
      /**
       * <code>int32 mloop = 1;</code>
       */
      public Builder setMloop(int value) {
        
        mloop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mloop = 1;</code>
       */
      public Builder clearMloop() {
        
        mloop_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MonitorL)
    }

    // @@protoc_insertion_point(class_scope:MonitorL)
    private static final com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL();
    }

    public static com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonitorL>
        PARSER = new com.google.protobuf.AbstractParser<MonitorL>() {
      @java.lang.Override
      public MonitorL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonitorL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonitorL> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonitorL> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.Monitor.MonitorOuterClass.MonitorL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RectangleM_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RectangleM_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitorL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitorL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025monitor/monitor.proto\"\031\n\nRectangleM\022\013\n" +
      "\003pid\030\001 \001(\005\"\031\n\010MonitorL\022\r\n\005mloop\030\001 \001(\00527\n" +
      "\007Monitor\022,\n\016getMonitorData\022\013.RectangleM\032" +
      "\t.MonitorL\"\0000\001B4\n2com.bmts.heating.commo" +
      "ns.grpc.lib.services.Monitorb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RectangleM_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RectangleM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RectangleM_descriptor,
        new java.lang.String[] { "Pid", });
    internal_static_MonitorL_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MonitorL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitorL_descriptor,
        new java.lang.String[] { "Mloop", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
