// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pattern/pattern.proto

package com.bmts.heating.commons.grpc.lib.services.Pattern;

public final class PatternOuterClass {
  private PatternOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RectangleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Rectangle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pid = 1;</code>
     */
    int getPid();

    /**
     * <code>string pname = 2;</code>
     */
    java.lang.String getPname();
    /**
     * <code>string pname = 2;</code>
     */
    com.google.protobuf.ByteString
        getPnameBytes();

    /**
     * <code>string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code Rectangle}
   */
  public  static final class Rectangle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Rectangle)
      RectangleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rectangle.newBuilder() to construct.
    private Rectangle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rectangle() {
      pid_ = 0;
      pname_ = "";
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Rectangle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Rectangle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Rectangle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.class, com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int PNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object pname_;
    /**
     * <code>string pname = 2;</code>
     */
    public java.lang.String getPname() {
      java.lang.Object ref = pname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pname_ = s;
        return s;
      }
    }
    /**
     * <code>string pname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPnameBytes() {
      java.lang.Object ref = pname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pid_ != 0) {
        output.writeInt32(1, pid_);
      }
      if (!getPnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pname_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      if (!getPnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pname_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle other = (com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle) obj;

      boolean result = true;
      result = result && (getPid()
          == other.getPid());
      result = result && getPname()
          .equals(other.getPname());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (37 * hash) + PNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPname().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Rectangle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Rectangle)
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.RectangleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Rectangle_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Rectangle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.class, com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pid_ = 0;

        pname_ = "";

        address_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Rectangle_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle build() {
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle result = new com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle(this);
        result.pid_ = pid_;
        result.pname_ = pname_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle.getDefaultInstance()) return this;
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (!other.getPname().isEmpty()) {
          pname_ = other.pname_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pid_ ;
      /**
       * <code>int32 pid = 1;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>int32 pid = 1;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pid = 1;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pname_ = "";
      /**
       * <code>string pname = 2;</code>
       */
      public java.lang.String getPname() {
        java.lang.Object ref = pname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPnameBytes() {
        java.lang.Object ref = pname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pname = 2;</code>
       */
      public Builder setPname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pname = 2;</code>
       */
      public Builder clearPname() {
        
        pname_ = getDefaultInstance().getPname();
        onChanged();
        return this;
      }
      /**
       * <code>string pname = 2;</code>
       */
      public Builder setPnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Rectangle)
    }

    // @@protoc_insertion_point(class_scope:Rectangle)
    private static final com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle();
    }

    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rectangle>
        PARSER = new com.google.protobuf.AbstractParser<Rectangle>() {
      @java.lang.Override
      public Rectangle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rectangle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rectangle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rectangle> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Rectangle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FeatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Feature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 location = 1;</code>
     */
    int getLocation();
  }
  /**
   * Protobuf type {@code Feature}
   */
  public  static final class Feature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Feature)
      FeatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Feature.newBuilder() to construct.
    private Feature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Feature() {
      location_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Feature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              location_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Feature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Feature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.class, com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    private int location_;
    /**
     * <code>int32 location = 1;</code>
     */
    public int getLocation() {
      return location_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (location_ != 0) {
        output.writeInt32(1, location_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (location_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature)) {
        return super.equals(obj);
      }
      com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature other = (com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature) obj;

      boolean result = true;
      result = result && (getLocation()
          == other.getLocation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Feature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Feature)
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.FeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Feature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Feature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.class, com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.Builder.class);
      }

      // Construct using com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        location_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.internal_static_Feature_descriptor;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature getDefaultInstanceForType() {
        return com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.getDefaultInstance();
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature build() {
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature buildPartial() {
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature result = new com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature(this);
        result.location_ = location_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature) {
          return mergeFrom((com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature other) {
        if (other == com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature.getDefaultInstance()) return this;
        if (other.getLocation() != 0) {
          setLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int location_ ;
      /**
       * <code>int32 location = 1;</code>
       */
      public int getLocation() {
        return location_;
      }
      /**
       * <code>int32 location = 1;</code>
       */
      public Builder setLocation(int value) {
        
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 location = 1;</code>
       */
      public Builder clearLocation() {
        
        location_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Feature)
    }

    // @@protoc_insertion_point(class_scope:Feature)
    private static final com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature();
    }

    public static com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Feature>
        PARSER = new com.google.protobuf.AbstractParser<Feature>() {
      @java.lang.Override
      public Feature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Feature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Feature> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bmts.heating.commons.grpc.lib.services.Pattern.PatternOuterClass.Feature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rectangle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rectangle_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Feature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025pattern/pattern.proto\"8\n\tRectangle\022\013\n\003" +
      "pid\030\001 \001(\005\022\r\n\005pname\030\002 \001(\t\022\017\n\007address\030\003 \001(" +
      "\t\"\033\n\007Feature\022\020\n\010location\030\001 \001(\00523\n\007Patter" +
      "n\022(\n\014ListFeatures\022\n.Rectangle\032\010.Feature\"" +
      "\0000\001B4\n2com.bmts.heating.commons.grpc.lib" +
      ".services.Patternb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rectangle_descriptor,
        new java.lang.String[] { "Pid", "Pname", "Address", });
    internal_static_Feature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Feature_descriptor,
        new java.lang.String[] { "Location", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
